name: Auto Run Job

on:
  schedule:
    - cron: '*/10 * * * *'  # Menjalankan setiap 10 menit
  workflow_dispatch:        # Memungkinkan pemicu manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Jalankan Skrip Anda
        run: |
          echo "Menjalankan tugas otomatis setiap 10 menit"
          # Tambahkan perintah atau skrip Anda di sini
